steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',' us-central1-docker.pkg.dev/thematic-vertex-463206-a5/tasleem6/myimage:tag1', '.']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/thematic-vertex-463206-a5/tasleem6/myimage:tag1']
options:
  logging: CLOUD_LOGGING_ONLY
